import { DataSource } from "typeorm";
import { Game, GameCategory, GameStatus } from "../entities/game.entity";

export class GamesSeed {
  constructor(private dataSource: DataSource) {}

  async run(): Promise<void> {
    const gameRepository = this.dataSource.getRepository(Game);

    const games = [
      // MOBA Games
      {
        name: "Mobile Legends: Bang Bang",
        slug: "mobile-legends",
        description:
          "Mobile MOBA game with 5v5 battles, extremely popular in Indonesia with millions of players",
        category: GameCategory.MOBA,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/mobile-legends-thumb.jpg",
        banner: "/images/games/mobile-legends-banner.jpg",
        metadata: {
          publisher: "Moonton",
          releaseDate: "2016-07-14",
          platforms: ["Android", "iOS"],
          genres: ["MOBA", "Strategy", "Action"],
          rating: "T",
          playerCount: { min: 1, max: 10 },
          region: "Global",
          serverRegions: ["Asia", "Indonesia"],
        },
        features: {
          hasChat: true,
          hasVoice: true,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: true,
          hasLeaderboards: true,
        },
        popularityScore: 98,
        userCount: 2500000,
      },
      {
        name: "Arena of Valor",
        slug: "arena-of-valor",
        description: "Fast-paced MOBA with unique heroes and intense battles",
        category: GameCategory.MOBA,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/arena-of-valor-thumb.jpg",
        banner: "/images/games/arena-of-valor-banner.jpg",
        metadata: {
          publisher: "Tencent Games",
          releaseDate: "2016-10-14",
          platforms: ["Android", "iOS"],
          genres: ["MOBA", "Strategy"],
          rating: "T",
          playerCount: { min: 1, max: 10 },
        },
        features: {
          hasChat: true,
          hasVoice: true,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: true,
          hasLeaderboards: true,
        },
        popularityScore: 85,
        userCount: 800000,
      },

      // FPS Games
      {
        name: "PUBG Mobile",
        slug: "pubg-mobile",
        description:
          "Battle royale shooter with intense survival gameplay, very popular in Indonesia",
        category: GameCategory.FPS,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/pubg-mobile-thumb.jpg",
        banner: "/images/games/pubg-mobile-banner.jpg",
        metadata: {
          publisher: "PUBG Corporation",
          releaseDate: "2018-03-19",
          platforms: ["Android", "iOS"],
          genres: ["FPS", "Battle Royale", "Survival"],
          rating: "T",
          playerCount: { min: 1, max: 100 },
          region: "Global",
          serverRegions: ["Asia", "Indonesia"],
        },
        features: {
          hasChat: true,
          hasVoice: true,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: true,
          hasLeaderboards: true,
        },
        popularityScore: 92,
        userCount: 2200000,
      },
      {
        name: "Free Fire",
        slug: "free-fire",
        description: "Fast-paced battle royale with unique characters",
        category: GameCategory.FPS,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/free-fire-thumb.jpg",
        banner: "/images/games/free-fire-banner.jpg",
        metadata: {
          publisher: "Garena",
          releaseDate: "2017-09-30",
          platforms: ["Android", "iOS"],
          genres: ["FPS", "Battle Royale"],
          rating: "T",
          playerCount: { min: 1, max: 50 },
        },
        features: {
          hasChat: true,
          hasVoice: true,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: true,
          hasLeaderboards: true,
        },
        popularityScore: 88,
        userCount: 1800000,
      },

      // Battle Royale Games
      {
        name: "Genshin Impact",
        slug: "genshin-impact",
        description: "Open-world action RPG with stunning graphics",
        category: GameCategory.RPG,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/genshin-impact-thumb.jpg",
        banner: "/images/games/genshin-impact-banner.jpg",
        metadata: {
          publisher: "miHoYo",
          releaseDate: "2020-09-28",
          platforms: ["Android", "iOS", "PC", "PS4"],
          genres: ["RPG", "Action", "Adventure"],
          rating: "T",
          playerCount: { min: 1, max: 4 },
        },
        features: {
          hasChat: true,
          hasVoice: false,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: false,
          hasLeaderboards: true,
        },
        popularityScore: 92,
        userCount: 1200000,
      },

      // Strategy Games
      {
        name: "Clash of Clans",
        slug: "clash-of-clans",
        description: "Build your village and battle other players",
        category: GameCategory.STRATEGY,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/clash-of-clans-thumb.jpg",
        banner: "/images/games/clash-of-clans-banner.jpg",
        metadata: {
          publisher: "Supercell",
          releaseDate: "2012-08-02",
          platforms: ["Android", "iOS"],
          genres: ["Strategy", "Base Building"],
          rating: "T",
          playerCount: { min: 1, max: 50 },
        },
        features: {
          hasChat: true,
          hasVoice: false,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: true,
          hasLeaderboards: true,
        },
        popularityScore: 87,
        userCount: 900000,
      },
      {
        name: "Clash Royale",
        slug: "clash-royale",
        description: "Real-time strategy card game with tower defense",
        category: GameCategory.STRATEGY,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/clash-royale-thumb.jpg",
        banner: "/images/games/clash-royale-banner.jpg",
        metadata: {
          publisher: "Supercell",
          releaseDate: "2016-03-02",
          platforms: ["Android", "iOS"],
          genres: ["Strategy", "Card Game"],
          rating: "T",
          playerCount: { min: 1, max: 2 },
        },
        features: {
          hasChat: true,
          hasVoice: false,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: true,
          hasLeaderboards: true,
        },
        popularityScore: 83,
        userCount: 700000,
      },

      // Sports Games
      {
        name: "eFootball PES 2024",
        slug: "efootball-pes-2024",
        description: "Realistic football simulation game",
        category: GameCategory.SPORTS,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/efootball-pes-thumb.jpg",
        banner: "/images/games/efootball-pes-banner.jpg",
        metadata: {
          publisher: "Konami",
          releaseDate: "2023-09-14",
          platforms: ["Android", "iOS", "PC", "PS4", "PS5"],
          genres: ["Sports", "Simulation"],
          rating: "E",
          playerCount: { min: 1, max: 22 },
        },
        features: {
          hasChat: true,
          hasVoice: true,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: true,
          hasLeaderboards: true,
        },
        popularityScore: 78,
        userCount: 500000,
      },

      // Racing Games
      {
        name: "Asphalt 9: Legends",
        slug: "asphalt-9-legends",
        description: "High-octane racing with stunning graphics",
        category: GameCategory.RACING,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/asphalt-9-thumb.jpg",
        banner: "/images/games/asphalt-9-banner.jpg",
        metadata: {
          publisher: "Gameloft",
          releaseDate: "2018-07-25",
          platforms: ["Android", "iOS"],
          genres: ["Racing", "Action"],
          rating: "T",
          playerCount: { min: 1, max: 8 },
        },
        features: {
          hasChat: true,
          hasVoice: false,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: true,
          hasLeaderboards: true,
        },
        popularityScore: 75,
        userCount: 400000,
      },

      // Fighting Games
      {
        name: "Street Fighter: Duel",
        slug: "street-fighter-duel",
        description: "Mobile fighting game with classic characters",
        category: GameCategory.FIGHTING,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/street-fighter-duel-thumb.jpg",
        banner: "/images/games/street-fighter-duel-banner.jpg",
        metadata: {
          publisher: "Capcom",
          releaseDate: "2023-02-28",
          platforms: ["Android", "iOS"],
          genres: ["Fighting", "Action"],
          rating: "T",
          playerCount: { min: 1, max: 2 },
        },
        features: {
          hasChat: true,
          hasVoice: false,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: true,
          hasLeaderboards: true,
        },
        popularityScore: 72,
        userCount: 300000,
      },

      // Puzzle Games
      {
        name: "Candy Crush Saga",
        slug: "candy-crush-saga",
        description: "Addictive match-3 puzzle game",
        category: GameCategory.PUZZLE,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/candy-crush-thumb.jpg",
        banner: "/images/games/candy-crush-banner.jpg",
        metadata: {
          publisher: "King",
          releaseDate: "2012-04-12",
          platforms: ["Android", "iOS", "Facebook"],
          genres: ["Puzzle", "Casual"],
          rating: "E",
          playerCount: { min: 1, max: 1 },
        },
        features: {
          hasChat: false,
          hasVoice: false,
          hasVideo: false,
          hasStreaming: false,
          hasTournaments: false,
          hasLeaderboards: true,
        },
        popularityScore: 70,
        userCount: 250000,
      },

      // Additional Popular Indonesian Games
      {
        name: "Call of Duty: Mobile",
        slug: "call-of-duty-mobile",
        description:
          "Official Call of Duty mobile game with intense multiplayer battles",
        category: GameCategory.FPS,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/cod-mobile-thumb.jpg",
        banner: "/images/games/cod-mobile-banner.jpg",
        metadata: {
          publisher: "Activision",
          releaseDate: "2019-10-01",
          platforms: ["Android", "iOS"],
          genres: ["FPS", "Action", "Multiplayer"],
          rating: "T",
          playerCount: { min: 1, max: 100 },
          region: "Global",
          serverRegions: ["Asia", "Indonesia"],
        },
        features: {
          hasChat: true,
          hasVoice: true,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: true,
          hasLeaderboards: true,
        },
        popularityScore: 89,
        userCount: 1800000,
      },
      {
        name: "Valorant Mobile",
        slug: "valorant-mobile",
        description: "Tactical shooter with unique agents and abilities",
        category: GameCategory.FPS,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/valorant-mobile-thumb.jpg",
        banner: "/images/games/valorant-mobile-banner.jpg",
        metadata: {
          publisher: "Riot Games",
          releaseDate: "2024-01-01",
          platforms: ["Android", "iOS"],
          genres: ["FPS", "Tactical", "Strategy"],
          rating: "T",
          playerCount: { min: 5, max: 10 },
          region: "Global",
          serverRegions: ["Asia", "Indonesia"],
        },
        features: {
          hasChat: true,
          hasVoice: true,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: true,
          hasLeaderboards: true,
        },
        popularityScore: 85,
        userCount: 1200000,
      },
      {
        name: "Honkai: Star Rail",
        slug: "honkai-star-rail",
        description: "Space fantasy RPG with turn-based combat",
        category: GameCategory.RPG,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/honkai-star-rail-thumb.jpg",
        banner: "/images/games/honkai-star-rail-banner.jpg",
        metadata: {
          publisher: "miHoYo",
          releaseDate: "2023-04-26",
          platforms: ["Android", "iOS", "PC"],
          genres: ["RPG", "Turn-based", "Strategy"],
          rating: "T",
          playerCount: { min: 1, max: 4 },
          region: "Global",
          serverRegions: ["Asia", "Indonesia"],
        },
        features: {
          hasChat: true,
          hasVoice: false,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: false,
          hasLeaderboards: true,
        },
        popularityScore: 88,
        userCount: 950000,
      },
      {
        name: "Honkai Impact 3rd",
        slug: "honkai-impact-3rd",
        description: "Action RPG with stunning anime-style graphics",
        category: GameCategory.RPG,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/honkai-impact-thumb.jpg",
        banner: "/images/games/honkai-impact-banner.jpg",
        metadata: {
          publisher: "miHoYo",
          releaseDate: "2016-10-14",
          platforms: ["Android", "iOS", "PC"],
          genres: ["RPG", "Action", "Anime"],
          rating: "T",
          playerCount: { min: 1, max: 4 },
          region: "Global",
          serverRegions: ["Asia", "Indonesia"],
        },
        features: {
          hasChat: true,
          hasVoice: false,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: false,
          hasLeaderboards: true,
        },
        popularityScore: 82,
        userCount: 650000,
      },
      {
        name: "FIFA Mobile",
        slug: "fifa-mobile",
        description:
          "Official FIFA mobile football game with real players and teams",
        category: GameCategory.SPORTS,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/fifa-mobile-thumb.jpg",
        banner: "/images/games/fifa-mobile-banner.jpg",
        metadata: {
          publisher: "EA Sports",
          releaseDate: "2016-10-11",
          platforms: ["Android", "iOS"],
          genres: ["Sports", "Football", "Simulation"],
          rating: "E",
          playerCount: { min: 1, max: 22 },
          region: "Global",
          serverRegions: ["Asia", "Indonesia"],
        },
        features: {
          hasChat: true,
          hasVoice: true,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: true,
          hasLeaderboards: true,
        },
        popularityScore: 80,
        userCount: 750000,
      },
      {
        name: "Subway Surfers",
        slug: "subway-surfers",
        description:
          "Endless runner game with colorful graphics and simple controls",
        category: GameCategory.CASUAL,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/subway-surfers-thumb.jpg",
        banner: "/images/games/subway-surfers-banner.jpg",
        metadata: {
          publisher: "Kiloo",
          releaseDate: "2012-05-24",
          platforms: ["Android", "iOS"],
          genres: ["Casual", "Runner", "Arcade"],
          rating: "E",
          playerCount: { min: 1, max: 1 },
          region: "Global",
          serverRegions: ["Asia", "Indonesia"],
        },
        features: {
          hasChat: false,
          hasVoice: false,
          hasVideo: false,
          hasStreaming: false,
          hasTournaments: false,
          hasLeaderboards: true,
        },
        popularityScore: 75,
        userCount: 500000,
      },
      {
        name: "Temple Run 2",
        slug: "temple-run-2",
        description: "Classic endless runner with temple exploration theme",
        category: GameCategory.CASUAL,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/temple-run-2-thumb.jpg",
        banner: "/images/games/temple-run-2-banner.jpg",
        metadata: {
          publisher: "Imangi Studios",
          releaseDate: "2013-01-17",
          platforms: ["Android", "iOS"],
          genres: ["Casual", "Runner", "Adventure"],
          rating: "E",
          playerCount: { min: 1, max: 1 },
          region: "Global",
          serverRegions: ["Asia", "Indonesia"],
        },
        features: {
          hasChat: false,
          hasVoice: false,
          hasVideo: false,
          hasStreaming: false,
          hasTournaments: false,
          hasLeaderboards: true,
        },
        popularityScore: 68,
        userCount: 350000,
      },
      {
        name: "8 Ball Pool",
        slug: "8-ball-pool",
        description: "Realistic pool game with multiplayer matches",
        category: GameCategory.SPORTS,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/8-ball-pool-thumb.jpg",
        banner: "/images/games/8-ball-pool-banner.jpg",
        metadata: {
          publisher: "Miniclip",
          releaseDate: "2010-07-01",
          platforms: ["Android", "iOS", "Web"],
          genres: ["Sports", "Pool", "Multiplayer"],
          rating: "E",
          playerCount: { min: 1, max: 2 },
          region: "Global",
          serverRegions: ["Asia", "Indonesia"],
        },
        features: {
          hasChat: true,
          hasVoice: false,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: true,
          hasLeaderboards: true,
        },
        popularityScore: 72,
        userCount: 450000,
      },
      {
        name: "Ludo King",
        slug: "ludo-king",
        description: "Classic Ludo board game with online multiplayer",
        category: GameCategory.BOARD,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/ludo-king-thumb.jpg",
        banner: "/images/games/ludo-king-banner.jpg",
        metadata: {
          publisher: "Gametion Technologies",
          releaseDate: "2016-01-01",
          platforms: ["Android", "iOS", "Web"],
          genres: ["Board Game", "Strategy", "Multiplayer"],
          rating: "E",
          playerCount: { min: 2, max: 4 },
          region: "Global",
          serverRegions: ["Asia", "Indonesia"],
        },
        features: {
          hasChat: true,
          hasVoice: false,
          hasVideo: false,
          hasStreaming: false,
          hasTournaments: true,
          hasLeaderboards: true,
        },
        popularityScore: 78,
        userCount: 600000,
      },
      {
        name: "Chess.com",
        slug: "chess-com",
        description: "Online chess platform with millions of players worldwide",
        category: GameCategory.BOARD,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/chess-com-thumb.jpg",
        banner: "/images/games/chess-com-banner.jpg",
        metadata: {
          publisher: "Chess.com",
          releaseDate: "2007-01-01",
          platforms: ["Android", "iOS", "Web"],
          genres: ["Board Game", "Strategy", "Educational"],
          rating: "E",
          playerCount: { min: 1, max: 2 },
          region: "Global",
          serverRegions: ["Asia", "Indonesia"],
        },
        features: {
          hasChat: true,
          hasVoice: false,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: true,
          hasLeaderboards: true,
        },
        popularityScore: 85,
        userCount: 800000,
      },
      {
        name: "Among Us",
        slug: "among-us",
        description:
          "Social deduction game where players work together or deceive",
        category: GameCategory.SOCIAL,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/among-us-thumb.jpg",
        banner: "/images/games/among-us-banner.jpg",
        metadata: {
          publisher: "InnerSloth",
          releaseDate: "2018-06-15",
          platforms: ["Android", "iOS", "PC", "Nintendo Switch"],
          genres: ["Social", "Strategy", "Multiplayer"],
          rating: "T",
          playerCount: { min: 4, max: 10 },
          region: "Global",
          serverRegions: ["Asia", "Indonesia"],
        },
        features: {
          hasChat: true,
          hasVoice: true,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: false,
          hasLeaderboards: true,
        },
        popularityScore: 76,
        userCount: 400000,
      },
      {
        name: "Roblox",
        slug: "roblox",
        description: "Platform for creating and playing user-generated games",
        category: GameCategory.SANDBOX,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/roblox-thumb.jpg",
        banner: "/images/games/roblox-banner.jpg",
        metadata: {
          publisher: "Roblox Corporation",
          releaseDate: "2006-09-01",
          platforms: ["Android", "iOS", "PC", "Xbox"],
          genres: ["Sandbox", "Creative", "Social"],
          rating: "E",
          playerCount: { min: 1, max: 100 },
          region: "Global",
          serverRegions: ["Asia", "Indonesia"],
        },
        features: {
          hasChat: true,
          hasVoice: true,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: false,
          hasLeaderboards: true,
        },
        popularityScore: 82,
        userCount: 1100000,
      },
      {
        name: "Minecraft",
        slug: "minecraft",
        description: "Block-based sandbox game with endless possibilities",
        category: GameCategory.SANDBOX,
        status: GameStatus.ACTIVE,
        thumbnail: "/images/games/minecraft-thumb.jpg",
        banner: "/images/games/minecraft-banner.jpg",
        metadata: {
          publisher: "Mojang Studios",
          releaseDate: "2011-11-18",
          platforms: ["Android", "iOS", "PC", "Xbox", "PlayStation"],
          genres: ["Sandbox", "Creative", "Adventure"],
          rating: "E",
          playerCount: { min: 1, max: 8 },
          region: "Global",
          serverRegions: ["Asia", "Indonesia"],
        },
        features: {
          hasChat: true,
          hasVoice: true,
          hasVideo: false,
          hasStreaming: true,
          hasTournaments: false,
          hasLeaderboards: false,
        },
        popularityScore: 90,
        userCount: 1300000,
      },
    ];

    for (const gameData of games) {
      const existingGame = await gameRepository.findOne({
        where: { slug: gameData.slug },
      });

      if (!existingGame) {
        const game = gameRepository.create(gameData);
        await gameRepository.save(game);
        console.log(`✅ Seeded game: ${game.name}`);
      } else {
        console.log(`⏭️  Game already exists: ${gameData.name}`);
      }
    }

    console.log("🎮 Games seeding completed!");
  }
}
